// Generated by https://quicktype.io

export interface Assets {
  models: Models;
  airpedia: Record<string, string>;
}

export interface Models {
  optimized: Record<string, string>;
  minigame: Record<string, string>;
  images: Images;
  patches: Patches;
  generic: Generic;
}

export type Generic = Record<string, string>;

export interface Images {
  gold: Record<string, string>;
  silver: Record<string, string>;
  paper: Record<string, string>;
}

export type Patches = Record<string, string>;
