// Generated by https://quicktype.io

export interface CapturePayload {
  lat: number;
  lon: number;
  alt: number;
  speed: number;
  reg: string;
  callsign: string;
  gpsLat: number;
  gpsLon: number;
  radarLat: number;
  radarLon: number;
  radarRange: number;
  distance: number;
  associatedAirportId: number;
  flightId: number;
  track: number;
  icon: number;
  status: number;
  timestamp: number;
  onGround: boolean;
  source: number;
  model: string;
  xp: number;
  xpUserBonus: number;
  coverage: number;
  cloudiness: number;
  imageLarge: string;
  imageThumb: string;
  imageCopy: string;
  glow: boolean;
  coins: number;
  newAirport: boolean;
  hex: string;
}
